version: '3.8'

services:
  clickhouse:
    image: clickhouse/clickhouse-server:25.4.2.31
    container_name: thedus_clickhouse
    logging:
      driver: none
    ports:
      - "9000:9000"
      - "8123:8123"
    healthcheck:
      test: wget --no-verbose --tries=1 --spider localhost:8123/ping || exit 1
      interval: 2s
      timeout: 2s
      retries: 16
    environment:
      CLICKHOUSE_DB: thedus_tests
      CLICKHOUSE_USER: thedus_tests
      CLICKHOUSE_PASSWORD: thedus_tests
